plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    api(include("io.github.spair:imgui-java-binding:$imgui_version"))
    api(include(("io.github.spair:imgui-java-lwjgl3:$imgui_version"))) {
        exclude group: 'org.lwjgl'
        exclude group: 'org.lwjgl.lwjgl'
    }
    api(include("io.github.classgraph:classgraph:$classgraph_version"))
    api(include("io.github.toolfactory:narcissus:$narcissus_version"))

    runtimeOnly(include("io.github.spair:imgui-java-natives-windows:$imgui_version"))
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

dependencies {
}

remapJar {
    destinationDirectory = file("../builds/")
}
