plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs '../libs'
    }
}

dependencies {
    jarJar(api(clientAdditionalRuntimeClasspath("io.github.spair:imgui-java-binding:$imgui_version")))
    jarJar(api(clientAdditionalRuntimeClasspath("io.github.spair:imgui-java-lwjgl3:$imgui_version"))) {
        exclude group: 'org.lwjgl'
        exclude group: 'org.lwjgl.lwjgl'
    }
    jarJar(clientAdditionalRuntimeClasspath("io.github.spair:imgui-java-natives-windows:$imgui_version"))

    jarJar(api(clientAdditionalRuntimeClasspath("io.github.classgraph:classgraph:$classgraph_version")))
    jarJar(api(clientAdditionalRuntimeClasspath("io.github.toolfactory:narcissus:$narcissus_version")))
}

jar {
    destinationDirectory = file("../builds/")
}

sourceSets.main.resources { srcDir 'src/generated/resources' }